---
title: "Louis Bennett Lab One"
output: 
  html_document:
    code_folding: hide
date: "2023-10-06"
---

# Question One

```{r}
rb <- function(theta1 = 1, theta2 = 1, a = 1, b = 1) a * (theta2 - theta1 ^ 2) ^ 2 + (b - theta1) ^ 2

rb2 <- function(theta = c(1 , 1), a = 1, b = 1) {
  res  <- rb(theta1 = theta[1], theta2 = theta[2], a = a, b = b)
  
  grad1 <- -4 * a * (theta[2] - theta[1] ^ 2) * theta[1] - 2 * (b - theta[1])
  
  grad2 <- 2 * a * (theta[2] - theta[1] ^ 2)
  
  grad <- c(grad1, grad2)
  
  Hess <- matrix(
    c(
      -4 * a * theta[2] + 12 * a * (theta[1]) ^ 2 + 2,
      -4 * a * theta[1],
      -4 * a * theta[1],
      2 * a
    ), 
    nrow  = 2, 
    byrow = T
  )
  
  list(
    f = res,
    g = grad,
    H = Hess
  )
}

rb2(c(1/2,1/2),
    a = 10,
    b = 1)
```

# Question Two

```{r}
theta1 <- seq(-1, 1.5, length = 100)
theta2 <- seq(-0.5, 1.5, length = 100)

M <- matrix(NA, nrow = 100, ncol = 100)

for (i in seq_along(theta1)){
  for (j in seq_along(theta2)){
    
    M[i,j] <- rb(theta1 = theta1[i], theta2 = theta2[j], a = 10, b = 1)
  }
}

lev <- c(0.03, 0.1, 0.3, 1, 3, 5, 10, 30)

contour(
  x = theta1,
  y = theta2,
  z = M,
  levels = lev,
  main = "Contours of the Rosenbrook function a=10, b=1"
)

abline(h = 1, lty = 2, lwd = 0.5)
abline(v = 1, lty = 2,lwd = 0.5)
points(c(1, 1), pch = 19)
```


# Question Three

```{r}
iter <- 0
theta <- c(-0.5, 0.5)
a <- 10
b <- 1
cutoff <- 10e-6

fnVals <- NULL

contour(
  x = theta1,
  y = theta2,
  z = M,
  levels = lev,
  main = "Contours of the Rosenbrook function a=10, b=1"
)

while(!sqrt(sum(rb2(theta, a, b)$g ^ 2)) <= cutoff) {
  iter <- iter + 1
  
  print(theta)
  
  points(x = theta[1], y = theta[2], pch = 19, col = "#b41313")
  
  
  iter_info <- rb2(theta, 10, 1)
  theta <- theta + c(solve(iter_info$H) %*% (-iter_info$g))
  fnVals[iter] <- rb(theta[1], theta[2], a, b)
}
```

```{r}
plot(fnVals)
```

# Question Four

```{r}
data_poisson <- tibble::tibble(
  covariate = c(1:13),
  response = c(12, 14, 33, 50, 67, 74, 123, 141, 165, 204, 253, 246, 240)
)

neg_loglik_poisson <- function(theta1, theta2, data) {
  par <- c(theta1,theta2)
  y <- data$response
  X <- model.matrix(~data$covariate)
  lin_pred <- X %*% par
  
  res <- t(y) %*% (X %*% par) - sum(exp(lin_pred)) - sum(lgamma(y + 1))

  - res
}

theta1 <- seq(from = 0, to = 4, length = 100)
theta2 <- seq(from = 0.1, to = 0.4, length = 100)

M <- matrix(NA, nrow = 100, ncol = 100)
for(i in seq_along(theta1)){
  for(j in seq_along(theta2)) {
     M[i, j] <- neg_loglik_poisson(theta1[i], theta2[j], data = data_poisson)
  }
}

lev <- c(90, 100, 150, 200, 300, 500, 800, 1000)

contour(x = theta1,
        y = theta2,
        z = M,
        levels = lev,
        xlab = expression(lambda),
        ylab = expression(beta))
```

# Question Five

